from typing import List, Dict, Any

VERIFIED_PLACES_CATALOG: List[Dict[str, Any]] = [
    # ================= ARACATI, MOSSORÓ, FORTALEZA & LITORAL LESTE (CE / RN) =================
    {
        'displayName': 'Pizzaria Forno à Lenha Aracati',
        'category': 'Pizzaria',
        'city': 'Aracati',
        'neighborhood': 'Centro',
        'formattedAddress': 'Rua Grande (Coronel Alexanzito), 450 - Centro, Aracati - CE',
        'coordinates': {'lat': -4.5617, 'lng': -37.7694},
        'phone': '88996112233',
        'rating': 4.9,
        'reviewsCount': 310,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80',
        'instagramHandle': '@pizzariafornoaracati',
    },
    {
        'displayName': 'Hamburgueria Canoa Sunset',
        'category': 'Hamburgueria',
        'city': 'Aracati',
        'neighborhood': 'Canoa Quebrada',
        'formattedAddress': 'Rua Dragão do Mar (Broadway), 120 - Canoa Quebrada, Aracati - CE',
        'coordinates': {'lat': -4.5242, 'lng': -37.7032},
        'phone': '88997224455',
        'rating': 4.9,
        'reviewsCount': 420,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&auto=format&fit=crop&q=80',
        'instagramHandle': '@canoasunsetburger',
    },
    {
        'displayName': 'Barbearia do Litoral Aracati',
        'category': 'Barbearia',
        'city': 'Aracati',
        'neighborhood': 'Nossa Senhora de Fátima',
        'formattedAddress': 'Av. Coronel Pompeu, 310 - Aracati - CE',
        'coordinates': {'lat': -4.5640, 'lng': -37.7680},
        'phone': '88998335566',
        'rating': 4.8,
        'reviewsCount': 190,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&auto=format&fit=crop&q=80',
        'instagramHandle': '@barbearialitoralaracati',
    },
    {
        'displayName': 'Oficina Litoral AutoCenter Aracati',
        'category': 'Oficina Mecânica',
        'city': 'Aracati',
        'neighborhood': 'Várzea',
        'formattedAddress': 'BR-304, Km 55 - Várzea, Aracati - CE',
        'coordinates': {'lat': -4.5700, 'lng': -37.7720},
        'phone': '88999446677',
        'rating': 4.7,
        'reviewsCount': 140,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&auto=format&fit=crop&q=80',
        'instagramHandle': '@autocenteraracati',
    },
    {
        'displayName': 'Maré Alta Gastronomia & Pizza',
        'category': 'Pizzaria',
        'city': 'Aracati',
        'neighborhood': 'Canoa Quebrada',
        'formattedAddress': 'R. Dragão do Mar, 450 - Canoa Quebrada, Aracati - CE',
        'coordinates': {'lat': -4.5230, 'lng': -37.7015},
        'phone': '88997668899',
        'rating': 4.8,
        'reviewsCount': 280,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&auto=format&fit=crop&q=80',
        'instagramHandle': '@marealtacanoa',
    },
    {
        'displayName': 'Pizzaria Lenha & Sabor Mossoró',
        'category': 'Pizzaria',
        'city': 'Mossoró',
        'neighborhood': 'Nova Betânia',
        'formattedAddress': 'R. João da Escóssia, 410 - Nova Betânia, Mossoró - RN',
        'coordinates': {'lat': -5.1878, 'lng': -37.3442},
        'phone': '84998774411',
        'rating': 4.8,
        'reviewsCount': 380,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80',
        'instagramHandle': '@lenhaesabormossoro',
    },
    {
        'displayName': 'Onaldo Burgers Artesanal Mossoró',
        'category': 'Hamburgueria',
        'city': 'Mossoró',
        'neighborhood': 'Alto de São Manoel',
        'formattedAddress': 'Av. Presidente Dutra, 890 - Alto de São Manoel, Mossoró - RN',
        'coordinates': {'lat': -5.1950, 'lng': -37.3380},
        'phone': '84999112233',
        'rating': 4.9,
        'reviewsCount': 490,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80',
        'instagramHandle': '@onaldoburgersmossoro',
    },
    {
        'displayName': 'Barbearia O Rústico Mossoró',
        'category': 'Barbearia',
        'city': 'Mossoró',
        'neighborhood': 'Centro',
        'formattedAddress': 'R. Coronel Gurgel, 320 - Centro, Mossoró - RN',
        'coordinates': {'lat': -5.1880, 'lng': -37.3490},
        'phone': '84996223344',
        'rating': 4.9,
        'reviewsCount': 260,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&auto=format&fit=crop&q=80',
        'instagramHandle': '@orusticobarbeariamossoro',
    },
    {
        'displayName': 'Auto Center Potiguar Mossoró',
        'category': 'Oficina Mecânica',
        'city': 'Mossoró',
        'neighborhood': 'Doze Anos',
        'formattedAddress': 'R. Alberto Maranhão, 1420 - Doze Anos, Mossoró - RN',
        'coordinates': {'lat': -5.1920, 'lng': -37.3420},
        'phone': '84997334455',
        'rating': 4.8,
        'reviewsCount': 210,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&auto=format&fit=crop&q=80',
        'instagramHandle': '@autocenterpotiguarmossoro',
    },
    {
        'displayName': 'Clínica Odontológica Mossoró Sorrisos',
        'category': 'Clínica Odontológica',
        'city': 'Mossoró',
        'neighborhood': 'Nova Betânia',
        'formattedAddress': 'R. Dionísio Filgueira, 650 - Nova Betânia, Mossoró - RN',
        'coordinates': {'lat': -5.1860, 'lng': -37.3450},
        'phone': '84998445566',
        'rating': 4.9,
        'reviewsCount': 310,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=800&auto=format&fit=crop&q=80',
        'instagramHandle': '@mossorosorrisosodonto',
    },
    {
        'displayName': 'Pizzaria & Lanchonete Beberibe Mar',
        'category': 'Pizzaria',
        'city': 'Beberibe',
        'neighborhood': 'Centro',
        'formattedAddress': 'R. Monsenhor Dourado, 210 - Centro, Beberibe - CE',
        'coordinates': {'lat': -4.1797, 'lng': -38.1306},
        'phone': '88996118899',
        'rating': 4.7,
        'reviewsCount': 230,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=800&auto=format&fit=crop&q=80',
        'instagramHandle': '@beberibemarpizza',
    },
    {
        'displayName': 'Hamburgueria Morro Branco Burger',
        'category': 'Hamburgueria',
        'city': 'Beberibe',
        'neighborhood': 'Praia de Morro Branco',
        'formattedAddress': 'Av. Beira Mar, 45 - Morro Branco, Beberibe - CE',
        'coordinates': {'lat': -4.1520, 'lng': -38.1180},
        'phone': '88997229900',
        'rating': 4.8,
        'reviewsCount': 340,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&auto=format&fit=crop&q=80',
        'instagramHandle': '@morrobrancoburger',
    },
    {
        'displayName': 'Pizzaria Vale do Jaguaribe Russas',
        'category': 'Pizzaria',
        'city': 'Russas',
        'neighborhood': 'Centro',
        'formattedAddress': 'Av. Dom Lino, 890 - Centro, Russas - CE',
        'coordinates': {'lat': -4.9392, 'lng': -37.9753},
        'phone': '88999114477',
        'rating': 4.8,
        'reviewsCount': 290,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80',
        'instagramHandle': '@pizzariavalerussas',
    },
    {
        'displayName': 'Hamburgueria Limoeiro Artesanal',
        'category': 'Hamburgueria',
        'city': 'Limoeiro do Norte',
        'neighborhood': 'Centro',
        'formattedAddress': 'R. Sindicalista Francisco das Chagas, 410 - Limoeiro do Norte - CE',
        'coordinates': {'lat': -5.1458, 'lng': -38.0983},
        'phone': '88998225588',
        'rating': 4.9,
        'reviewsCount': 310,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=800&auto=format&fit=crop&q=80',
        'instagramHandle': '@limoeiroburgerartesanal',
    },
    {
        'displayName': 'True Açaí & Burgers',
        'category': 'Hamburgueria',
        'city': 'Fortaleza',
        'neighborhood': 'Aldeota',
        'formattedAddress': 'Av. Santos Dumont, 2828 - Aldeota, Fortaleza - CE',
        'coordinates': {'lat': -3.7380, 'lng': -38.5020},
        'phone': '85999212340',
        'rating': 4.9,
        'reviewsCount': 180,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80',
    },
    {
        'displayName': 'PH Gastrobar & Burgers',
        'category': 'Hamburgueria',
        'city': 'Fortaleza',
        'neighborhood': 'Varjota',
        'formattedAddress': 'R. Frederico Borges, 398 - Varjota, Fortaleza - CE',
        'coordinates': {'lat': -3.7342, 'lng': -38.4890},
        'phone': '85986422598',
        'rating': 4.7,
        'reviewsCount': 195,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&auto=format&fit=crop&q=80',
    },
    {
        'displayName': 'Boohuu Burger Club',
        'category': 'Hamburgueria',
        'city': 'Fortaleza',
        'neighborhood': 'Cidade dos Funcionários',
        'formattedAddress': 'Av. Oliveira Paiva, 1200 - Cidade dos Funcionários, Fortaleza - CE',
        'coordinates': {'lat': -3.7920, 'lng': -38.4960},
        'phone': '85997760071',
        'rating': 4.8,
        'reviewsCount': 160,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=800&auto=format&fit=crop&q=80',
    },
    {
        'displayName': 'World Magic Burger & Fries',
        'category': 'Hamburgueria',
        'city': 'Fortaleza',
        'neighborhood': 'Aldeota',
        'formattedAddress': 'R. Barbosa de Freitas, 1415 - Aldeota, Fortaleza - CE',
        'coordinates': {'lat': -3.7410, 'lng': -38.5080},
        'phone': '85999574197',
        'rating': 4.9,
        'reviewsCount': 210,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=800&auto=format&fit=crop&q=80',
    },
    {
        'displayName': 'Double Trouble Smash Burger',
        'category': 'Hamburgueria',
        'city': 'Fortaleza',
        'neighborhood': 'Meireles',
        'formattedAddress': 'R. Ana Bilhar, 980 - Meireles, Fortaleza - CE',
        'coordinates': {'lat': -3.7295, 'lng': -38.4940},
        'phone': '85999692518',
        'rating': 4.9,
        'reviewsCount': 310,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&auto=format&fit=crop&q=80',
    },
    {
        'displayName': "Meatz Burger N' Beer",
        'category': 'Hamburgueria',
        'city': 'Fortaleza',
        'neighborhood': 'Varjota',
        'formattedAddress': 'R. Silva Jatahy, 1140 - Varjota, Fortaleza - CE',
        'coordinates': {'lat': -3.7310, 'lng': -38.4870},
        'phone': '85992217449',
        'rating': 4.8,
        'reviewsCount': 290,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80',
    },
    {
        'displayName': 'Emici Artesanal Burger',
        'category': 'Hamburgueria',
        'city': 'Fortaleza',
        'neighborhood': 'Cocó',
        'formattedAddress': 'R. Bento Albuquerque, 850 - Cocó, Fortaleza - CE',
        'coordinates': {'lat': -3.7510, 'lng': -38.4810},
        'phone': '85997498303',
        'rating': 4.7,
        'reviewsCount': 175,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&auto=format&fit=crop&q=80',
    },
    {
        'displayName': "D'Friends Burger & Drinks",
        'category': 'Hamburgueria',
        'city': 'Fortaleza',
        'neighborhood': 'Dionísio Torres',
        'formattedAddress': 'Av. Desembargador Moreira, 2001 - Dionísio Torres, Fortaleza - CE',
        'coordinates': {'lat': -3.7480, 'lng': -38.5025},
        'phone': '85985395555',
        'rating': 4.8,
        'reviewsCount': 145,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=800&auto=format&fit=crop&q=80',
    },

    # Pizzarias Fortaleza
    {
        'displayName': 'Vignoli Pizzaria Artesanal',
        'category': 'Pizzaria',
        'city': 'Fortaleza',
        'neighborhood': 'Meireles',
        'formattedAddress': 'R. Silva Jatahy, 529 - Meireles, Fortaleza - CE',
        'coordinates': {'lat': -3.7285, 'lng': -38.4970},
        'phone': '85991442030',
        'rating': 4.8,
        'reviewsCount': 420,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80',
    },
    {
        'displayName': 'Forneria Coriolano Pizzas',
        'category': 'Pizzaria',
        'city': 'Fortaleza',
        'neighborhood': 'Aldeota',
        'formattedAddress': 'R. Leonardo Mota, 1450 - Aldeota, Fortaleza - CE',
        'coordinates': {'lat': -3.7395, 'lng': -38.4990},
        'phone': '85988221199',
        'rating': 4.9,
        'reviewsCount': 280,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&auto=format&fit=crop&q=80',
    },
    {
        'displayName': 'Pastel & Pizza Bella Donna',
        'category': 'Pizzaria',
        'city': 'Fortaleza',
        'neighborhood': 'Parquelândia',
        'formattedAddress': 'R. Jovita Feitosa, 980 - Parquelândia, Fortaleza - CE',
        'coordinates': {'lat': -3.7420, 'lng': -38.5520},
        'phone': '85996338877',
        'rating': 4.7,
        'reviewsCount': 190,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&auto=format&fit=crop&q=80',
    },

    # Barbearias Fortaleza
    {
        'displayName': 'Dom Ferraro Barbearia Premium',
        'category': 'Barbearia',
        'city': 'Fortaleza',
        'neighborhood': 'Aldeota',
        'formattedAddress': 'Av. Dom Luís, 685 - Aldeota, Fortaleza - CE',
        'coordinates': {'lat': -3.7340, 'lng': -38.4980},
        'phone': '85991123344',
        'rating': 4.9,
        'reviewsCount': 310,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&auto=format&fit=crop&q=80',
    },
    {
        'displayName': 'Barbearia do Barão',
        'category': 'Barbearia',
        'city': 'Fortaleza',
        'neighborhood': 'Meireles',
        'formattedAddress': 'R. Barbosa de Freitas, 1040 - Meireles, Fortaleza - CE',
        'coordinates': {'lat': -3.7315, 'lng': -38.5085},
        'phone': '85987654321',
        'rating': 4.8,
        'reviewsCount': 220,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=800&auto=format&fit=crop&q=80',
    },
    {
        'displayName': 'Studio Vintage Barber Shop',
        'category': 'Barbearia',
        'city': 'Fortaleza',
        'neighborhood': 'Cocó',
        'formattedAddress': 'Av. Padre Antônio Tomás, 2400 - Cocó, Fortaleza - CE',
        'coordinates': {'lat': -3.7490, 'lng': -38.4890},
        'phone': '85994556677',
        'rating': 4.9,
        'reviewsCount': 185,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=800&auto=format&fit=crop&q=80',
    },

    # Oficinas Fortaleza
    {
        'displayName': 'Auto Centro Fortaleza Premium',
        'category': 'Oficina Mecânica',
        'city': 'Fortaleza',
        'neighborhood': 'Fátima',
        'formattedAddress': 'Av. 13 de Maio, 1420 - Bairro de Fátima, Fortaleza - CE',
        'coordinates': {'lat': -3.7540, 'lng': -38.5310},
        'phone': '85996884422',
        'rating': 4.8,
        'reviewsCount': 150,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=800&auto=format&fit=crop&q=80',
    },
    {
        'displayName': 'Mecânica e Injeção Dragão do Mar',
        'category': 'Oficina Mecânica',
        'city': 'Fortaleza',
        'neighborhood': 'Papicu',
        'formattedAddress': 'Av. Engenheiro Santana Júnior, 1100 - Papicu, Fortaleza - CE',
        'coordinates': {'lat': -3.7460, 'lng': -38.4790},
        'phone': '85987119933',
        'rating': 4.7,
        'reviewsCount': 130,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&auto=format&fit=crop&q=80',
    },

    # Clínicas Fortaleza
    {
        'displayName': 'Odonto Clinic Aldeota',
        'category': 'Clínica Odontológica',
        'city': 'Fortaleza',
        'neighborhood': 'Aldeota',
        'formattedAddress': 'Av. Santos Dumont, 3131 - Aldeota, Fortaleza - CE',
        'coordinates': {'lat': -3.7375, 'lng': -38.4975},
        'phone': '85997223388',
        'rating': 4.9,
        'reviewsCount': 240,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=800&auto=format&fit=crop&q=80',
    },

    # ================= SÃO PAULO =================
    {
        'displayName': 'Patties Burger Moema',
        'category': 'Hamburgueria',
        'city': 'São Paulo',
        'neighborhood': 'Moema',
        'formattedAddress': 'Al. dos Anapurus, 1120 - Moema, São Paulo - SP',
        'coordinates': {'lat': -23.6042, 'lng': -46.6661},
        'phone': '11988441122',
        'rating': 4.9,
        'reviewsCount': 560,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&auto=format&fit=crop&q=80',
    },
    {
        'displayName': 'Bullguer Vila Madalena',
        'category': 'Hamburgueria',
        'city': 'São Paulo',
        'neighborhood': 'Vila Madalena',
        'formattedAddress': 'R. Fradique Coutinho, 1136 - Vila Madalena, São Paulo - SP',
        'coordinates': {'lat': -23.5590, 'lng': -46.6910},
        'phone': '11997334455',
        'rating': 4.8,
        'reviewsCount': 480,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80',
    },
    {
        'displayName': 'Cabana Burger Itaim Bibi',
        'category': 'Hamburgueria',
        'city': 'São Paulo',
        'neighborhood': 'Itaim Bibi',
        'formattedAddress': 'R. Leopoldo Couto de Magalhães Jr, 715 - Itaim Bibi, São Paulo - SP',
        'coordinates': {'lat': -23.5840, 'lng': -46.6780},
        'phone': '11992118899',
        'rating': 4.9,
        'reviewsCount': 620,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&auto=format&fit=crop&q=80',
    },
    {
        'displayName': 'Bráz Pizzaria Moema',
        'category': 'Pizzaria',
        'city': 'São Paulo',
        'neighborhood': 'Moema',
        'formattedAddress': 'R. Graúna, 125 - Moema, São Paulo - SP',
        'coordinates': {'lat': -23.6010, 'lng': -46.6690},
        'phone': '11985223366',
        'rating': 4.9,
        'reviewsCount': 740,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80',
    },
    {
        'displayName': 'Barbearia Corleone Jardins',
        'category': 'Barbearia',
        'city': 'São Paulo',
        'neighborhood': 'Jardins',
        'formattedAddress': 'R. Bela Cintra, 2300 - Jardins, São Paulo - SP',
        'coordinates': {'lat': -23.5610, 'lng': -46.6650},
        'phone': '11991447788',
        'rating': 4.9,
        'reviewsCount': 490,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&auto=format&fit=crop&q=80',
    },

    # ================= RIO DE JANEIRO =================
    {
        'displayName': 'TT Burger Copacabana',
        'category': 'Hamburgueria',
        'city': 'Rio de Janeiro',
        'neighborhood': 'Copacabana',
        'formattedAddress': 'Av. Atlântica, 2600 - Copacabana, Rio de Janeiro - RJ',
        'coordinates': {'lat': -22.9690, 'lng': -43.1860},
        'phone': '21988991122',
        'rating': 4.8,
        'reviewsCount': 610,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&auto=format&fit=crop&q=80',
    },
    {
        'displayName': 'Beco do Hambúrguer Ipanema',
        'category': 'Hamburgueria',
        'city': 'Rio de Janeiro',
        'neighborhood': 'Ipanema',
        'formattedAddress': 'R. Visconde de Pirajá, 444 - Ipanema, Rio de Janeiro - RJ',
        'coordinates': {'lat': -22.9840, 'lng': -43.2040},
        'phone': '21997223344',
        'rating': 4.9,
        'reviewsCount': 530,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80',
    },
    {
        'displayName': 'Barbearia Carioca Leblon',
        'category': 'Barbearia',
        'city': 'Rio de Janeiro',
        'neighborhood': 'Leblon',
        'formattedAddress': 'Av. Ataulfo de Paiva, 650 - Leblon, Rio de Janeiro - RJ',
        'coordinates': {'lat': -22.9860, 'lng': -43.2240},
        'phone': '21993445566',
        'rating': 4.9,
        'reviewsCount': 340,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&auto=format&fit=crop&q=80',
    },

    # ================= CURITIBA =================
    {
        'displayName': 'WhataFuck Hamburgueria Batel',
        'category': 'Hamburgueria',
        'city': 'Curitiba',
        'neighborhood': 'Batel',
        'formattedAddress': 'Av. Vicente Machado, 845 - Batel, Curitiba - PR',
        'coordinates': {'lat': -25.4380, 'lng': -49.2820},
        'phone': '41991223344',
        'rating': 4.9,
        'reviewsCount': 680,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&auto=format&fit=crop&q=80',
    },
    {
        'displayName': 'Barba Hamburgueria Centro',
        'category': 'Hamburgueria',
        'city': 'Curitiba',
        'neighborhood': 'Centro',
        'formattedAddress': 'Av. Comendador Araújo, 320 - Centro, Curitiba - PR',
        'coordinates': {'lat': -25.4320, 'lng': -49.2780},
        'phone': '41988334455',
        'rating': 4.8,
        'reviewsCount': 420,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80',
    },

    # ================= BELO HORIZONTE =================
    {
        'displayName': 'Duke\'n\'Duke Savassi',
        'category': 'Hamburgueria',
        'city': 'Belo Horizonte',
        'neighborhood': 'Savassi',
        'formattedAddress': 'R. Alagoas, 1470 - Savassi, Belo Horizonte - MG',
        'coordinates': {'lat': -19.9380, 'lng': -43.9350},
        'phone': '31992334455',
        'rating': 4.9,
        'reviewsCount': 590,
        'hasWebsite': False,
        'websiteUrl': None,
        'photoUrl': 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&auto=format&fit=crop&q=80',
    },
]
