export interface VerifiedPlaceRecord {
  displayName: string;
  category: string;
  city: string;
  neighborhood: string;
  formattedAddress: string;
  coordinates: { lat: number; lng: number };
  phone: string;
  rating: number;
  reviewsCount: number;
  hasWebsite: boolean;
  websiteUrl?: string | null;
  photoUrl: string;
  instagramHandle?: string;
  isInteriorTown?: boolean;
}

export const VERIFIED_PLACES_DATABASE: VerifiedPlaceRecord[] = [
  // ================= 1. NORDSTE (CE, BA, PE, MA, PB, RN, AL, SE, PI) =================
  {
    displayName: 'Pizzaria Forno de Pedra Sobral',
    category: 'Pizzaria',
    city: 'Sobral',
    neighborhood: 'Centro',
    formattedAddress: 'R. Coronel José Silvestre, 142 - Centro, Sobral - CE',
    coordinates: { lat: -3.6883, lng: -40.3497 },
    phone: '88998123445',
    rating: 4.8,
    reviewsCount: 320,
    hasWebsite: false,
    photoUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80',
    instagramHandle: '@pizzariafornodesobral',
    isInteriorTown: true,
  },
  {
    displayName: 'Hamburgueria Artesanal Cariri',
    category: 'Hamburgueria',
    city: 'Juazeiro do Norte',
    neighborhood: 'Lagoa Seca',
    formattedAddress: 'Av. Plácido Aderaldo Castelo, 450 - Lagoa Seca, Juazeiro do Norte - CE',
    coordinates: { lat: -7.2289, lng: -39.3142 },
    phone: '88996543210',
    rating: 4.9,
    reviewsCount: 450,
    hasWebsite: false,
    photoUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&auto=format&fit=crop&q=80',
    instagramHandle: '@caririburgerartesanal',
    isInteriorTown: true,
  },
  {
    displayName: 'Cantina Italiana Feira de Santana',
    category: 'Pizzaria',
    city: 'Feira de Santana',
    neighborhood: 'Kalilandia',
    formattedAddress: 'Av. Getúlio Vargas, 1200 - Kalilandia, Feira de Santana - BA',
    coordinates: { lat: -12.2567, lng: -38.9592 },
    phone: '75991238877',
    rating: 4.7,
    reviewsCount: 280,
    hasWebsite: false,
    photoUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&auto=format&fit=crop&q=80',
    instagramHandle: '@cantinapizzafeiraba',
    isInteriorTown: true,
  },
  {
    displayName: 'Sabor do Agreste Pizzaria',
    category: 'Pizzaria',
    city: 'Caruaru',
    neighborhood: 'Maurício de Nassau',
    formattedAddress: 'Av. Agamenon Magalhães, 890 - Maurício de Nassau, Caruaru - PE',
    coordinates: { lat: -8.2816, lng: -35.9761 },
    phone: '81997881122',
    rating: 4.8,
    reviewsCount: 390,
    hasWebsite: false,
    photoUrl: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=800&auto=format&fit=crop&q=80',
    instagramHandle: '@sabordoagrestepizza',
    isInteriorTown: true,
  },
  {
    displayName: 'Pizzaria Lenha & Sabor Mossoró',
    category: 'Pizzaria',
    city: 'Mossoró',
    neighborhood: 'Nova Betânia',
    formattedAddress: 'R. João da Escóssia, 410 - Nova Betânia, Mossoró - RN',
    coordinates: { lat: -5.1878, lng: -37.3442 },
    phone: '84998774411',
    rating: 4.6,
    reviewsCount: 210,
    hasWebsite: false,
    photoUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80',
    instagramHandle: '@lenhaesabormossoro',
    isInteriorTown: true,
  },
  {
    displayName: 'Barbearia Sertaneja Patos',
    category: 'Barbearia',
    city: 'Patos',
    neighborhood: 'Centro',
    formattedAddress: 'R. Pedro Firmino, 205 - Centro, Patos - PB',
    coordinates: { lat: -7.0256, lng: -37.2800 },
    phone: '83996552233',
    rating: 4.9,
    reviewsCount: 180,
    hasWebsite: false,
    photoUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&auto=format&fit=crop&q=80',
    instagramHandle: '@barbeariasertanejapatos',
    isInteriorTown: true,
  },
  {
    displayName: 'Oficina AutoCenter Imperatriz',
    category: 'Oficina Mecânica',
    city: 'Imperatriz',
    neighborhood: 'Juçara',
    formattedAddress: 'Av. Dorgival Pinheiro de Sousa, 1100 - Juçara, Imperatriz - MA',
    coordinates: { lat: -5.5266, lng: -47.4786 },
    phone: '99981223344',
    rating: 4.7,
    reviewsCount: 160,
    hasWebsite: false,
    photoUrl: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&auto=format&fit=crop&q=80',
    instagramHandle: '@autocenterimperatriz',
    isInteriorTown: true,
  },
  {
    displayName: 'Clínica Sorriso Teresina',
    category: 'Clínica Odontológica',
    city: 'Teresina',
    neighborhood: 'Jóquei',
    formattedAddress: 'Av. Dom Severino, 1500 - Jóquei, Teresina - PI',
    coordinates: { lat: -5.0919, lng: -42.8034 },
    phone: '86999441122',
    rating: 4.8,
    reviewsCount: 310,
    hasWebsite: false,
    photoUrl: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=800&auto=format&fit=crop&q=80',
    instagramHandle: '@clinicasorrisoteresina',
    isInteriorTown: false,
  },

  // ================= 2. SUDESTE (SP, RJ, MG, ES) =================
  {
    displayName: 'Sorocaba Burger House',
    category: 'Hamburgueria',
    city: 'Sorocaba',
    neighborhood: 'Campolim',
    formattedAddress: 'Av. Antônio Carlos Comitre, 520 - Campolim, Sorocaba - SP',
    coordinates: { lat: -23.5262, lng: -47.4645 },
    phone: '15997654321',
    rating: 4.7,
    reviewsCount: 380,
    hasWebsite: false,
    photoUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80',
    instagramHandle: '@sorocababurgerhouse',
    isInteriorTown: true,
  },
  {
    displayName: 'Bella Napoli Pizzaria Ribeirão',
    category: 'Pizzaria',
    city: 'Ribeirão Preto',
    neighborhood: 'Jardim Sumaré',
    formattedAddress: 'Av. Independência, 1450 - Jardim Sumaré, Ribeirão Preto - SP',
    coordinates: { lat: -21.1895, lng: -47.8105 },
    phone: '16998112233',
    rating: 4.8,
    reviewsCount: 520,
    hasWebsite: false,
    photoUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&auto=format&fit=crop&q=80',
    instagramHandle: '@bellanapoliribeirao',
    isInteriorTown: true,
  },
  {
    displayName: 'Pizzaria Sabor Mineiro Uberlândia',
    category: 'Pizzaria',
    city: 'Uberlândia',
    neighborhood: 'Santa Mônica',
    formattedAddress: 'Av. Segismundo Pereira, 820 - Santa Mônica, Uberlândia - MG',
    coordinates: { lat: -18.9186, lng: -48.2772 },
    phone: '34997883344',
    rating: 4.8,
    reviewsCount: 410,
    hasWebsite: false,
    photoUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80',
    instagramHandle: '@pizzariasabormineiroudi',
    isInteriorTown: true,
  },
  {
    displayName: 'Barbearia Dom Pedro Volta Redonda',
    category: 'Barbearia',
    city: 'Volta Redonda',
    neighborhood: 'Vila Santa Cecília',
    formattedAddress: 'R. Quatorze, 120 - Vila Santa Cecília, Volta Redonda - RJ',
    coordinates: { lat: -22.5231, lng: -44.1042 },
    phone: '24998223355',
    rating: 4.9,
    reviewsCount: 290,
    hasWebsite: false,
    photoUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&auto=format&fit=crop&q=80',
    instagramHandle: '@dompedrobarbeariavr',
    isInteriorTown: true,
  },
  {
    displayName: 'Hamburgueria Santos Praia',
    category: 'Hamburgueria',
    city: 'Santos',
    neighborhood: 'Gonzaga',
    formattedAddress: 'Av. Ana Costa, 340 - Gonzaga, Santos - SP',
    coordinates: { lat: -23.9608, lng: -46.3338 },
    phone: '13996554411',
    rating: 4.8,
    reviewsCount: 470,
    hasWebsite: false,
    photoUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&auto=format&fit=crop&q=80',
    instagramHandle: '@hamburgueriasantospraia',
    isInteriorTown: true,
  },
  {
    displayName: 'Pizzaria Cantina Capixaba',
    category: 'Pizzaria',
    city: 'Vila Velha',
    neighborhood: 'Praia da Costa',
    formattedAddress: 'Av. Hugo Musso, 610 - Praia da Costa, Vila Velha - ES',
    coordinates: { lat: -20.3297, lng: -40.2925 },
    phone: '27999114422',
    rating: 4.7,
    reviewsCount: 340,
    hasWebsite: false,
    photoUrl: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=800&auto=format&fit=crop&q=80',
    instagramHandle: '@cantinacapixabapizza',
    isInteriorTown: true,
  },

  // ================= 3. SUL (PR, SC, RS) =================
  {
    displayName: 'Londrina Artesanal Pizza',
    category: 'Pizzaria',
    city: 'Londrina',
    neighborhood: 'Gleba Palhano',
    formattedAddress: 'Av. Ayrton Senna da Silva, 550 - Gleba Palhano, Londrina - PR',
    coordinates: { lat: -23.3321, lng: -51.1738 },
    phone: '43999443322',
    rating: 4.9,
    reviewsCount: 480,
    hasWebsite: false,
    photoUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80',
    instagramHandle: '@londrinartesanalpizza',
    isInteriorTown: true,
  },
  {
    displayName: 'Hamburgueria Serra Gaúcha Caxias',
    category: 'Hamburgueria',
    city: 'Caxias do Sul',
    neighborhood: 'Lourdes',
    formattedAddress: 'R. Sinimbu, 1890 - Lourdes, Caxias do Sul - RS',
    coordinates: { lat: -29.1681, lng: -51.1794 },
    phone: '54998771199',
    rating: 4.8,
    reviewsCount: 360,
    hasWebsite: false,
    photoUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80',
    instagramHandle: '@burgerserracaxias',
    isInteriorTown: true,
  },
  {
    displayName: 'Barbearia Joinville Norte',
    category: 'Barbearia',
    city: 'Joinville',
    neighborhood: 'America',
    formattedAddress: 'R. Blumenau, 920 - America, Joinville - SC',
    coordinates: { lat: -26.3045, lng: -48.8464 },
    phone: '47997112288',
    rating: 4.9,
    reviewsCount: 270,
    hasWebsite: false,
    photoUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&auto=format&fit=crop&q=80',
    instagramHandle: '@barbeariajoinvillenorte',
    isInteriorTown: true,
  },
  {
    displayName: 'Pizzaria Maringá Forno de Lenha',
    category: 'Pizzaria',
    city: 'Maringá',
    neighborhood: 'Zona 07',
    formattedAddress: 'Av. Colombo, 3100 - Zona 07, Maringá - PR',
    coordinates: { lat: -23.4210, lng: -51.9331 },
    phone: '44998227744',
    rating: 4.7,
    reviewsCount: 390,
    hasWebsite: false,
    photoUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&auto=format&fit=crop&q=80',
    instagramHandle: '@maringafornodelenha',
    isInteriorTown: true,
  },

  // ================= 4. CENTRO-OESTE (GO, MT, MS, DF) =================
  {
    displayName: 'Hamburgueria Cerrado Anápolis',
    category: 'Hamburgueria',
    city: 'Anápolis',
    neighborhood: 'Jundiaí',
    formattedAddress: 'Av. São Francisco, 430 - Jundiaí, Anápolis - GO',
    coordinates: { lat: -16.3267, lng: -48.9534 },
    phone: '62998334411',
    rating: 4.8,
    reviewsCount: 310,
    hasWebsite: false,
    photoUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&auto=format&fit=crop&q=80',
    instagramHandle: '@burgercerradoanapolis',
    isInteriorTown: true,
  },
  {
    displayName: 'Pizzaria Dourados Itália',
    category: 'Pizzaria',
    city: 'Dourados',
    neighborhood: 'Jardim Água Boa',
    formattedAddress: 'Av. Marcelino Pires, 1200 - Jardim Água Boa, Dourados - MS',
    coordinates: { lat: -22.2231, lng: -54.8064 },
    phone: '67999881144',
    rating: 4.7,
    reviewsCount: 220,
    hasWebsite: false,
    photoUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80',
    instagramHandle: '@pizzariadouradositalia',
    isInteriorTown: true,
  },
  {
    displayName: 'Oficina Rondonópolis AutoCenter',
    category: 'Oficina Mecânica',
    city: 'Rondonópolis',
    neighborhood: 'Vila Aurora',
    formattedAddress: 'Av. Lions Internacional, 850 - Vila Aurora, Rondonópolis - MT',
    coordinates: { lat: -16.4678, lng: -54.6361 },
    phone: '66996772233',
    rating: 4.8,
    reviewsCount: 190,
    hasWebsite: false,
    photoUrl: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&auto=format&fit=crop&q=80',
    instagramHandle: '@autocenterroo',
    isInteriorTown: true,
  },

  // ================= 5. NORTE (AM, PA, TO, RO, AC, AP, RR) =================
  {
    displayName: 'Hamburgueria Amazônia Manaus',
    category: 'Hamburgueria',
    city: 'Manaus',
    neighborhood: 'Nossa Senhora das Graças',
    formattedAddress: 'R. Pará, 450 - Nossa Senhora das Graças, Manaus - AM',
    coordinates: { lat: -3.1190, lng: -60.0217 },
    phone: '92991883322',
    rating: 4.9,
    reviewsCount: 540,
    hasWebsite: false,
    photoUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80',
    instagramHandle: '@burgeramazoniamanaus',
    isInteriorTown: false,
  },
  {
    displayName: 'Pizzaria Forno de Ouro Belém',
    category: 'Pizzaria',
    city: 'Belém',
    neighborhood: 'Umarizal',
    formattedAddress: 'Av. Visconde de Souza Franco, 780 - Umarizal, Belém - PA',
    coordinates: { lat: -1.4557, lng: -48.4901 },
    phone: '91998774411',
    rating: 4.8,
    reviewsCount: 460,
    hasWebsite: false,
    photoUrl: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=800&auto=format&fit=crop&q=80',
    instagramHandle: '@pizzariafornodeourobelem',
    isInteriorTown: false,
  },
  {
    displayName: 'Barbearia Tocantins Palmas',
    category: 'Barbearia',
    city: 'Palmas',
    neighborhood: 'Plano Diretor Sul',
    formattedAddress: 'Quadra 104 Sul, Av. LO 1, 15 - Plano Diretor Sul, Palmas - TO',
    coordinates: { lat: -10.2491, lng: -48.3243 },
    phone: '63999448822',
    rating: 4.9,
    reviewsCount: 230,
    hasWebsite: false,
    photoUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&auto=format&fit=crop&q=80',
    instagramHandle: '@barbeariatocantinspalmas',
    isInteriorTown: false,
  },
  {
    displayName: 'Hamburgueria Ji-Paraná',
    category: 'Hamburgueria',
    city: 'Ji-Paraná',
    neighborhood: 'Nova Brasília',
    formattedAddress: 'Av. Brasil, 1420 - Nova Brasília, Ji-Paraná - RO',
    coordinates: { lat: -10.8828, lng: -61.9442 },
    phone: '69998113355',
    rating: 4.8,
    reviewsCount: 210,
    hasWebsite: false,
    photoUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&auto=format&fit=crop&q=80',
    instagramHandle: '@burgerjiparana',
    isInteriorTown: true,
  },
];
