# Generated by Django 6.1 on 2026-08-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=255, unique=True, verbose_name='ID do Estabelecimento')),
                ('display_name', models.CharField(max_length=255, verbose_name='Nome do Local')),
                ('category', models.CharField(max_length=120, verbose_name='Categoria')),
                ('formatted_address', models.CharField(max_length=500, verbose_name='Endereço')),
                ('neighborhood', models.CharField(blank=True, max_length=120, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Cidade')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('has_website', models.BooleanField(default=False, verbose_name='Tem Website')),
                ('website_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL do Site')),
                ('has_whatsapp', models.BooleanField(default=True, verbose_name='Tem WhatsApp')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('raw_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone Cru')),
                ('rating', models.FloatField(default=4.5, verbose_name='Avaliação Google')),
                ('reviews_count', models.IntegerField(default=0, verbose_name='Qtd de Avaliações')),
                ('google_maps_uri', models.CharField(blank=True, max_length=500, verbose_name='Link Maps')),
                ('photo_url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Foto')),
                ('score_percentage', models.IntegerField(default=0, verbose_name='Score de Fechamento (%)')),
                ('classification', models.CharField(default='Baixa Prioridade', max_length=50, verbose_name='Classificação')),
                ('rationale', models.TextField(blank=True, verbose_name='Justificativa da IA/Heurística')),
                ('custom_pitch', models.TextField(blank=True, verbose_name='Pitch de WhatsApp')),
                ('crm_status', models.CharField(choices=[('Novo', 'Novo'), ('Contatado', 'Contatado'), ('Em Negociação', 'Em Negociação'), ('Fechado', 'Fechado')], default='Novo', max_length=50, verbose_name='Status no CRM')),
                ('is_saved', models.BooleanField(default=False, verbose_name='Lead Salvo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-score_percentage', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.CharField(max_length=500, verbose_name='URL do Repositório / Produto')),
                ('repo_name', models.CharField(max_length=200, verbose_name='Nome do Projeto')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('icp_data', models.JSONField(default=dict, verbose_name='Perfil de Cliente Ideal (ICP)')),
                ('core_value_prop', models.TextField(blank=True, verbose_name='Proposta de Valor')),
                ('search_keywords', models.JSONField(default=list, verbose_name='Palavras-chave Maps')),
                ('solved_pain_points', models.JSONField(default=list, verbose_name='Dores Resolvidas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TargetLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome da Localização')),
                ('city', models.CharField(max_length=120, verbose_name='Cidade')),
                ('state', models.CharField(default='BR', max_length=50, verbose_name='Estado/UF')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('zoom', models.IntegerField(default=14, verbose_name='Zoom Inicial')),
                ('is_custom', models.BooleanField(default=True, verbose_name='Criado pelo Usuário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
