# Generated by Django 6.1 on 2026-08-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Contato/Gerente'),
        ),
        migrations.AddField(
            model_name='lead',
            name='monthly_fee',
            field=models.FloatField(default=150.0, verbose_name='Mensalidade Recorrente (R$)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='setup_fee',
            field=models.FloatField(default=400.0, verbose_name='Taxa de Setup/Implantação (R$)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='timeline_logs',
            field=models.JSONField(default=list, verbose_name='Histórico de Interações'),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='crm_status',
            field=models.CharField(choices=[('Novo', 'Novo Lead'), ('Contatado', 'Contato Feito'), ('Demonstracao', 'Em Demonstração'), ('Fechado', 'Cliente Fechado'), ('Perdido', 'Perdido')], default='Novo', max_length=50, verbose_name='Status no CRM'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='is_saved',
            field=models.BooleanField(default=True, verbose_name='Lead Salvo no CRM'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas Internas & Objeções'),
        ),
    ]
